In [1]:
import pandas as pd
from pandas import json_normalize

In [2]:
df = pd.read_json('../datasets/EntityRecognitioninResumes.json', lines=True)
pd.set_option('display.max_colwidth', None)
df.head(5)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Abhishek Jha\nApplication Development Associate - Accenture\n\nBengaluru, Karnataka - Email me on Indeed: indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a\n\n• To work for an organization which provides me the opportunity to improve my skills\nand knowledge for my individual and company's growth in best possible ways.\n\nWilling to relocate to: Bangalore, Karnataka\n\nWORK EXPERIENCE\n\nApplication Development Associate\n\nAccenture -\n\nNovember 2017 to Present\n\nRole: Currently working on Chat-bot. Developing Backend Oracle PeopleSoft Queries\nfor the Bot which will be triggered based on given input. Also, Training the bot for different possible\nutterances (Both positive and negative), which will be given as\ninput by the user.\n\nEDUCATION\n\nB.E in Information science and engineering\n\nB.v.b college of engineering and technology -  Hubli, Karnataka\n\nAugust 2013 to June 2017\n\n12th in Mathematics\n\nWoodbine modern school\n\nApril 2011 to March 2013\n\n10th\n\nKendriya Vidyalaya\n\nApril 2001 to March 2011\n\nSKILLS\n\nC (Less than 1 year), Database (Less than 1 year), Database Management (Less than 1 year),\nDatabase Management System (Less than 1 year), Java (Less than 1 year)\n\nADDITIONAL INFORMATION\n\nTechnical Skills\n\nhttps://www.indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a?isid=rex-download&ikw=download-top&co=IN\n\n\n• Programming language: C, C++, Java\n• Oracle PeopleSoft\n• Internet Of Things\n• Machine Learning\n• Database Management System\n• Computer Networks\n• Operating System worked on: Linux, Windows, Mac\n\nNon - Technical Skills\n\n• Honest and Hard-Working\n• Tolerant and Flexible to Different Situations\n• Polite and Calm\n• Team-Player

In [3]:
print(df.columns)
df['extras'].unique

Index(['content', 'annotation', 'extras'], dtype='str')

<bound method Series.unique of 0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
215   NaN
216   NaN
217   NaN
218   NaN
219   NaN
Name: extras, Length: 220, dtype: float64>

In [4]:
df = df.drop(columns='extras')
print(df.columns)

Index(['content', 'annotation'], dtype='str')

In [5]:
first_resume_annotations = df['annotation'].iloc[0]
eda_friendly_df = json_normalize(first_resume_annotations)
print(eda_friendly_df.head())

               label  \
0           [Skills]
1           [Skills]
2     [College Name]
3     [College Name]
4  [Graduation Year]

                                                                                                                                                                                                                                                                                                                                                                              points
0  [{'start': 1295, 'end': 1621, 'text': '
• Programming language: C, C++, Java
• Oracle PeopleSoft
• Internet Of Things
• Machine Learning
• Database Management System
• Computer Networks
• Operating System worked on: Linux, Windows, Mac

Non - Technical Skills

• Honest and Hard-Working
• Tolerant and Flexible to Different Situations
• Polite and Calm
• Team-Player'}]
1                                                                                                                                                                         [{'start': 993, 'end': 1153, 'text': 'C (Less than 1 year), Database (Less than 1 year), Database Management (Less than 1 year),
Database Management System (Less than 1 year), Java (Less than 1 year)'}]
2                                                                                                                                                                                                                                                                                                                         [{'start': 939, 'end': 956, 'text': 'Kendriya Vidyalaya'}]
3                                                                                                                                                                                                                                                                                                                     [{'start': 883, 'end': 904, 'text': 'Woodbine modern school'}]
4                                                                                                                                                                                                                                                                                                                                      [{'start': 856, 'end': 860, 'text': '2017
'}]

In [6]:
all_data = []

for index, row in df.iterrows():
    
    for ann in row['annotation']:
        label = ann['label'][0] if ann['label'] else "None"
      
        text = ann['points'][0]['text']
        
        all_data.append({
            'resume_id': index, 
            'label': label, 
            'text': text.strip()
        })


clean_df = pd.DataFrame(all_data)


print(clean_df['label'].value_counts())

label
Companies worked at    729
Designation            521
Skills                 472
Location               430
College Name           330
Degree                 298
Graduation Year        254
Email Address          252
Name                   224
Years of Experience     44
UNKNOWN                  2
None                     2
Name: count, dtype: int64

In [7]:
clean_df[clean_df["label"] == "None"]

      resume_id label    text
1734         81  None  Oracle
2926        167  None   B.B.M

In [8]:
clean_df[clean_df["label"] == "UNKNOWN"]

      resume_id    label                  text
1247         61  UNKNOWN  Oracle 10g, 11g, 12c
3017        175  UNKNOWN                  2012

### CLEANING & PREPROCESS

In [9]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer